services:
  hikstatus:
    build: .
    container_name: hikstatus
    restart: always
    environment:
      - TZ=Asia/Tehran    
    ports:
      - '28888:28888'
    volumes:
      - ./data:/app/data
      - ./camera_names.csv:/app/camera_names.csv

networks:
  default:
    name: npm
    external: true